//! Platform clipboard access for Pasteport.
//!
//! One trait, [`ClipboardBackend`], with a real implementation per platform:
//!
//! * macOS uses `NSPasteboard` and its `changeCount`, so idle polling costs a
//!   single integer read.
//! * Linux delegates to `wl-clipboard` on Wayland or `xclip`/`xsel` on X11 and
//!   detects change by hashing the current contents.
//!
//! Nothing here knows about storage or policy: a backend's job is to hand a
//! [`NewClip`] to the caller and to write a payload back out.

#![warn(missing_debug_implementations)]

use std::time::Duration;

use pasteport_core::NewClip;

mod error;
mod watcher;

#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "macos")]
mod macos;

pub use error::{Error, Result};
pub use watcher::Watcher;

#[cfg(target_os = "linux")]
pub use linux::{LinuxClipboard, LinuxTool};
#[cfg(target_os = "macos")]
pub use macos::MacOsClipboard;

/// Content handed to a backend to place on the system clipboard.
#[derive(Debug, Clone, Copy)]
pub enum Payload<'a> {
    Text(&'a str),
    Image { bytes: &'a [u8], mime: &'a str },
}

/// A platform clipboard.
///
/// Implementations track their own change state, so [`poll`](Self::poll)
/// returns `Some` only when the clipboard actually changed since the last call.
pub trait ClipboardBackend: Send + std::fmt::Debug {
    /// Short name for logs and `pasteport status`.
    fn name(&self) -> &'static str;

    /// Return the current clipboard contents if they changed since the last
    /// poll, otherwise `None`.
    fn poll(&mut self) -> Result<Option<NewClip>>;

    /// Place `payload` on the clipboard.
    ///
    /// Implementations must also mark the resulting state as already-seen so
    /// the next [`poll`](Self::poll) does not report our own write as a new
    /// clip from the user.
    fn write(&mut self, payload: Payload<'_>) -> Result<()>;

    /// Read the clipboard unconditionally, ignoring change tracking.
    fn read_now(&mut self) -> Result<Option<NewClip>>;
}

/// Build the backend for the platform we are running on.
pub fn default_backend() -> Result<Box<dyn ClipboardBackend>> {
    #[cfg(target_os = "macos")]
    {
        Ok(Box::new(MacOsClipboard::new()?))
    }
    #[cfg(target_os = "linux")]
    {
        Ok(Box::new(LinuxClipboard::new()?))
    }
    #[cfg(not(any(target_os = "macos", target_os = "linux")))]
    {
        Err(Error::UnsupportedPlatform(std::env::consts::OS))
    }
}

/// Pasteboard markers that other apps use to say "do not archive this".
/// Pasteport honours all three; password managers rely on them.
pub const CONCEALED_MARKERS: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    // Wayland/X11 equivalents used by KeePassXC and friends.
    "x-kde-passwordManagerHint",
    "application/x-nextcloud-talk-secret",
];

/// True when any of the advertised clipboard types asks us not to store it.
pub fn is_concealed(types: &[String]) -> bool {
    types
        .iter()
        .any(|t| CONCEALED_MARKERS.iter().any(|m| t.eq_ignore_ascii_case(m)))
}

/// A sensible default poll interval, matching [`pasteport_core::Config`].
pub const DEFAULT_POLL_INTERVAL: Duration = Duration::from_millis(400);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_concealed_markers_case_insensitively() {
        assert!(is_concealed(
            &["org.nspasteboard.concealedtype".to_string()]
        ));
        assert!(is_concealed(&[
            "public.utf8-plain-text".to_string(),
            "org.nspasteboard.TransientType".to_string(),
        ]));
        assert!(is_concealed(&["x-kde-passwordManagerHint".to_string()]));
        assert!(!is_concealed(&["public.utf8-plain-text".to_string()]));
        assert!(!is_concealed(&[]));
    }
}
